// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDX7ZbBSYeG7YeMUlfY7kS-cPnreoclBkg',
    appId: '1:985541367403:web:148bcee69e3b8f0b3ac32e',
    messagingSenderId: '985541367403',
    projectId: 'fooddeliveryapp-62718',
    authDomain: 'fooddeliveryapp-62718.firebaseapp.com',
    storageBucket: 'fooddeliveryapp-62718.firebasestorage.app',
    measurementId: 'G-J1K5SZ2960',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJBh7x-3fhOmuhDwcGAoClDNYf8Gx6Vhw',
    appId: '1:985541367403:android:3e2fe43c8debdfcf3ac32e',
    messagingSenderId: '985541367403',
    projectId: 'fooddeliveryapp-62718',
    storageBucket: 'fooddeliveryapp-62718.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeY_qB7fJelrbSVb5LnSz-UW3j7HdRGOQ',
    appId: '1:985541367403:ios:6fee0c46477ef8bc3ac32e',
    messagingSenderId: '985541367403',
    projectId: 'fooddeliveryapp-62718',
    storageBucket: 'fooddeliveryapp-62718.firebasestorage.app',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeY_qB7fJelrbSVb5LnSz-UW3j7HdRGOQ',
    appId: '1:985541367403:ios:6fee0c46477ef8bc3ac32e',
    messagingSenderId: '985541367403',
    projectId: 'fooddeliveryapp-62718',
    storageBucket: 'fooddeliveryapp-62718.firebasestorage.app',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDX7ZbBSYeG7YeMUlfY7kS-cPnreoclBkg',
    appId: '1:985541367403:web:6a7685228d1330fd3ac32e',
    messagingSenderId: '985541367403',
    projectId: 'fooddeliveryapp-62718',
    authDomain: 'fooddeliveryapp-62718.firebaseapp.com',
    storageBucket: 'fooddeliveryapp-62718.firebasestorage.app',
    measurementId: 'G-F58JF00X3R',
  );
}
